package fraVentanaDin;

import java.awt.Dimension;

public class fraVentanaDin extends javax.swing.JFrame {
    
    String pos = "Centro";
    String coord = "300x300";
    
    fraVentana2 fr2 = new fraVentana2();
    
    public fraVentanaDin() {
        
        setTitle("Dimensiones y posiciones - " + pos + " – " + coord);
        setSize(300, 300);
        setMinimumSize(new Dimension(100, 100));
        setLocation(400, 200);
        
        fr2.setEnabled(true);
        fr2.setVisible(false);
        
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bntArribaDerecha = new javax.swing.JButton();
        bntArribaIzquierda = new javax.swing.JButton();
        btnAbajoDerecha = new javax.swing.JButton();
        btnAbajoIzquierda = new javax.swing.JButton();
        tglDimension = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(600, 600));
        setMinimumSize(new java.awt.Dimension(300, 300));
        setPreferredSize(new java.awt.Dimension(300, 300));

        jPanel1.setMaximumSize(new java.awt.Dimension(600, 600));
        jPanel1.setMinimumSize(new java.awt.Dimension(300, 300));
        jPanel1.setOpaque(false);

        bntArribaDerecha.setText("Arriba Derecha");
        bntArribaDerecha.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        bntArribaDerecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntArribaDerechaActionPerformed(evt);
            }
        });

        bntArribaIzquierda.setText("Arriba Izquierda");
        bntArribaIzquierda.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bntArribaIzquierda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntArribaIzquierdaActionPerformed(evt);
            }
        });

        btnAbajoDerecha.setText("Abajo Derecha");
        btnAbajoDerecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbajoDerechaActionPerformed(evt);
            }
        });

        btnAbajoIzquierda.setText("Abajo Izquieda");
        btnAbajoIzquierda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbajoIzquierdaActionPerformed(evt);
            }
        });

        tglDimension.setText("Aumenta dimension");
        tglDimension.setAlignmentY(0.0F);
        tglDimension.setFocusable(false);
        tglDimension.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tglDimension.setOpaque(true);
        tglDimension.setPreferredSize(new java.awt.Dimension(136, 23));
        tglDimension.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                tglDimensionItemStateChanged(evt);
            }
        });
        tglDimension.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglDimensionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bntArribaIzquierda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bntArribaDerecha))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAbajoIzquierda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAbajoDerecha)))
                .addGap(30, 30, 30))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tglDimension, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntArribaDerecha)
                    .addComponent(bntArribaIzquierda))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tglDimension, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAbajoIzquierda)
                    .addComponent(btnAbajoDerecha))
                .addGap(58, 58, 58))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntArribaIzquierdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntArribaIzquierdaActionPerformed

        fr2.setVisible(true);
        fr2.setLocation(0, 0);
        pos = "Arriba Izquierda";
        fr2.setText(pos);
        setTitle("Dimensiones y posiciones - " + pos + " – " + coord);
    }//GEN-LAST:event_bntArribaIzquierdaActionPerformed

    private void tglDimensionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglDimensionActionPerformed

        

    }//GEN-LAST:event_tglDimensionActionPerformed

    private void tglDimensionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_tglDimensionItemStateChanged

        int estado = evt.getStateChange();
        if (estado == evt.SELECTED) {
            tglDimension.setText("Disminuir Dimension");
            setSize(600, 600);
            coord = "600x600";
            setTitle("Dimensiones y posiciones - " + pos + " – " + coord);
            
        } else {
            tglDimension.setText("Aumentar Dimension");
            setSize(300, 300);
            coord = "300x300";
            setTitle("Dimensiones y posiciones - " + pos + " – " + coord);

        }

    }//GEN-LAST:event_tglDimensionItemStateChanged

    private void bntArribaDerechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntArribaDerechaActionPerformed

        fr2.setVisible(true);
        fr2.setLocation(600, 0);
        pos = "Arriba Derecha";
        fr2.setText(pos);
        setTitle("Dimensiones y posiciones - " + pos + " – " + coord);
    }//GEN-LAST:event_bntArribaDerechaActionPerformed

    private void btnAbajoIzquierdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbajoIzquierdaActionPerformed
        
        fr2.setVisible(true);
        fr2.setLocation(0, 400);
        pos = "Abajo Izquierda";
        fr2.setText(pos);
        setTitle("Dimensiones y posiciones - " + pos + " – " + coord);
    }//GEN-LAST:event_btnAbajoIzquierdaActionPerformed

    private void btnAbajoDerechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbajoDerechaActionPerformed

        fr2.setVisible(true);
        fr2.setLocation(600, 400);
        pos = "Abajo Derecha";
        fr2.setText(pos);
        setTitle("Dimensiones y posiciones - " + pos + " – " + coord);
    }//GEN-LAST:event_btnAbajoDerechaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fraVentanaDin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fraVentanaDin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fraVentanaDin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fraVentanaDin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fraVentanaDin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntArribaDerecha;
    private javax.swing.JButton bntArribaIzquierda;
    private javax.swing.JButton btnAbajoDerecha;
    private javax.swing.JButton btnAbajoIzquierda;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton tglDimension;
    // End of variables declaration//GEN-END:variables
}
