/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.vista;

import com.controlador.ControlarBD;
import com.modelo.Tablapapeleria;
import java.util.List;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;

/**
 *
 * @author usuario
 */
public class NuevoProducto extends javax.swing.JFrame {

    String msgError = "";
    List<Tablapapeleria> listaPapeleria;

    /**
     * Creates new form NuevoProducto
     */
    public NuevoProducto() {
        initComponents();
        setTitle("Nuevo producto");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtfCodigo = new javax.swing.JTextField();
        txtfProducto = new javax.swing.JTextField();
        txtfFamilia = new javax.swing.JTextField();
        txtfPrecio = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnNuevoProd = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setText("Código:");

        jLabel2.setText("Producto:");

        jLabel3.setText("Familia:");

        jLabel4.setText("Precio:");

        jLabel5.setText("Rellena todos los campos y pulsa \"Guardar\"");

        btnNuevoProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Add.png"))); // NOI18N
        btnNuevoProd.setText("Nuevo producto");
        btnNuevoProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoProdActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(64, 64, 64)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtfCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                                    .addComponent(txtfProducto)
                                    .addComponent(txtfFamilia)
                                    .addComponent(txtfPrecio))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(btnNuevoProd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtfProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtfFamilia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtfPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevoProd)
                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
private void crearLista() {
        ControlarBD controlarbd = new ControlarBD();
        listaPapeleria = controlarbd.findAll();
    }
    private void btnNuevoProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoProdActionPerformed
        // TODO add your handling code here:
        if (validarDatos()) {

            ControlarBD controlarbd = new ControlarBD();
            Tablapapeleria tablapapeleria = new Tablapapeleria();
            tablapapeleria.setCodigo(txtfCodigo.getText());
            tablapapeleria.setFamilia(txtfFamilia.getText());
            tablapapeleria.setPrecio(Double.parseDouble(txtfPrecio.getText()));
            tablapapeleria.setProducto(txtfProducto.getText());
            controlarbd.create(tablapapeleria);

            JOptionPane.showMessageDialog(this, "Producto nuevo creado correctamente", "Producto creado", JOptionPane.INFORMATION_MESSAGE);
            int respuestaConfirmacion = JOptionPane.showConfirmDialog(this, "¿Desea insertar otro producto?", "Salir", JOptionPane.YES_NO_OPTION);
            if (respuestaConfirmacion == 0) {
                limpiarFormulario();
            } else {
                salir();
            }

        } else {
            JOptionPane.showMessageDialog(this, msgError, "Error de validación", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnNuevoProdActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        limpiarFormulario();
    }//GEN-LAST:event_btnResetActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        MenuInicio menuMain = new MenuInicio();
        menuMain.setVisible(true);
    }//GEN-LAST:event_formWindowClosed
    private void limpiarFormulario() {
        txtfCodigo.setText("");
        txtfFamilia.setText("");
        txtfPrecio.setText("");
        txtfProducto.setText("");
    }

    private boolean validarDatos() {
        boolean validado = true;
        if (txtfCodigo.getText() == null || txtfCodigo.getText().equals("")) {
            msgError = "El campo codigo no puede estar vacío";
            validado = false;
            txtfCodigo.requestFocus();
        } else {
            if (txtfFamilia.getText() == null || txtfFamilia.getText().equals("")) {
                msgError = "El campo familia no puede estar vacío";
                validado = false;
                txtfFamilia.requestFocus();
            } else {
                if (txtfPrecio.getText() == null || txtfPrecio.getText().equals("")) {
                    msgError = "El campo precio no puede estar vacío";
                    validado = false;
                    txtfPrecio.requestFocus();
                } else {
                    if (!isNumeric(txtfPrecio.getText())) {
                        msgError = "El campo precio no es un valor numérico";
                        validado = false;
                        txtfPrecio.requestFocus();
                    } else {
                        if (txtfProducto.getText() == null || txtfProducto.getText().equals("")) {
                            msgError = "El campo producto no puede estar vacío";
                            validado = false;
                            txtfProducto.requestFocus();
                        } else {
                            crearLista();
                            for (int i = 0; i < listaPapeleria.size(); i++) {
                                if (listaPapeleria.get(i).getCodigo().equals(txtfCodigo.getText())) {
                                    msgError = "Ya existe un producto con ese código.";
                                    validado = false;
                                    txtfCodigo.requestFocus();
                                }
                            }
                        }
                    }
                }
            }
        }
        return validado;
    }

    private void salir() {
        MenuInicio ventana = new MenuInicio();
        ventana.setVisible(true);
        this.dispose();
    }

    private static boolean isNumeric(String cadena) {
        try {
            Double.parseDouble(cadena);
            return true;
        } catch (NumberFormatException nfe) {
            return false;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevoProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevoProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevoProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevoProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NuevoProducto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNuevoProd;
    private javax.swing.JButton btnReset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtfCodigo;
    private javax.swing.JTextField txtfFamilia;
    private javax.swing.JTextField txtfPrecio;
    private javax.swing.JTextField txtfProducto;
    // End of variables declaration//GEN-END:variables
}
